### ISSUE TITLE
Compatibility with phpunit 9.x

### ISSUE THREAD

**Issue by mvorisek** [ergebnis/phpunit-slow-test-detector#291]
This is a feature request. Please make this package compatible with phpunit 9.x so it can be used in projects that still need to support phpunit 9.x which is still very popular - https://packagist.org/packages/phpunit/phpunit/stats (about 70% market share).

![image](https://github.com/ergebnis/phpunit-slow-test-detector/assets/2228672/8e73533e-5ced-4062-9456-14d0b18a3515)

**Comment by localheinz** [comment]
@mvorisek 

Please convince @johnkary instead to merge https://github.com/johnkary/phpunit-speedtrap/pull/98.

**Comment by mvorisek** [comment]
I am aware of that PR, but this package seems to be well tested and maintained, so adding backcompatibility should not be that hard and can help this package become popular 🚀

**Comment by localheinz** [comment]
@mvorisek 

Let me think about it!

**Comment by mvorisek** [comment]
@localheinz I would really appretiate it, we need to support phpunit 9 & 10 via single dep

**Comment by localheinz** [comment]
Released as [`ergebnis/phpunit-slow-test-detector:2.4.0`](https://github.com/ergebnis/phpunit-slow-test-detector/releases/tag/2.4.0) - would be happy to find out it works for you, @mvorisek!

**Comment by mvorisek** [comment]
Awesome news, thank you @localheinz ❤️
