### ISSUE TITLE
Consider adding support for `phpunit/phpunit:^8`

### ISSUE THREAD

**Issue by localheinz** [ergebnis/phpunit-slow-test-detector#368]
Follows #291.

**Comment by mvorisek** [comment]
also all `^9` and `^10` should be tested to allow testing lowest versions like in https://github.com/atk4/ui/blob/5.0.0/.github/workflows/test-unit.yml#L141

**Comment by mvorisek** [comment]
@localheinz https://github.com/ergebnis/phpunit-slow-test-detector/blob/2.6.0/composer.json#L28 still needs to be changed to `^8 || ^9 || ^10`, this lib should not limit the minimal phpunit needed.

**Comment by localheinz** [comment]
Fixed with #394.

**Comment by localheinz** [comment]
@mvorisek 

I will see what I can do about widening version constraints, but I will not widen version constraints beyond what I can prove works.
