### ISSUE TITLE
Composer `InstalledVersions` not found

### ISSUE THREAD

**Issue by dantleech** [ergebnis/phpunit-slow-test-detector#620]
Hi @localheinz :wave: 

#### Steps required to reproduce the problem

1. Use enable and use this extensions as a PHAR then
2. Try and use `InstalledVersions` in a PHPUnit test case:

```
\Composer\InstalledVersions::getVersion('some/package')
```

#### Expected Result

Returns the composer package version for the given package.

#### Actual Result

"fail" with the warning:

```
include(phar:///data/.tools/phpunit/extension/phpunit-slow-test-detector.phar/vendor/composer/../composer/InstalledVersions.php): Failed to open stream: phar error: "vendor/composer/InstalledVersions.php" is not a file in phar "/data/.tools/phpunit/extension/phpunit-slow-test-detector.phar"
```

---

It seems that the slow-test-detector's PHAR `vendorcomposer/autoload_classmap.php` has the following entry:

```
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
```

and starting from version [2.15.1](https://github.com/ergebnis/phpunit-slow-test-detector/releases/tag/2.15.1) it no longer exists.

**Comment by dantleech** [comment]
... I can't actually reproduce this problem in isolation, I'll check later today when I can.

**Comment by localheinz** [comment]
Thank you, @dantleech - let me know if I should take a look!

**Comment by dantleech** [comment]
ok, I _could_ reproduce it I just wasn't showing the warning details :sweat_smile: 

see here:  https://github.com/dantleech/slow-test-dector-gh-620

**Comment by dantleech** [comment]
ok, it is due to adding the `src` directory somehow as this ensures that `vendor/composer/InstalledVersions.php` remains in place:

```diff
diff --git a/box.json b/box.json
index 7a107ea..a3d2ee6 100644
--- a/box.json
+++ b/box.json
@@ -5,9 +5,6 @@
     "KevinGH\\Box\\Compactor\\Php"
   ],
   "compression": "GZ",
-  "directories": [
-    "src/"
-  ],
   "files": [
     "manifest.xml"
   ],
```

**Comment by dantleech** [comment]
ok, and this is a "fix": https://github.com/ergebnis/phpunit-slow-test-detector/pull/621

Incidentally calling `InstalledVersions::getVersion('my/version')` returns the project's package version as expected - so I'm not sure how/why it's trying to autoload (and subsequently include `installed.php`) from the PHAR's vendor dir.

So I'm not sure I have the courage to call it a "fix" but it will at least preserve the original behavior.

**Comment by dantleech** [comment]
wow, thanks :tada:

**Comment by localheinz** [comment]
Thank you for reporting and fixing, @dantleech!
